finished dao3 hw
AndriiBardin/hw-dao3 pull request #1
Opened 2021-01-13 16:57 UTC by AndriiBardin

2021-01-13 17:16 UTC, YuraBondarenko requested changes

2021-01-13 17:16 UTC, YuraBondarenko commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +    }
тебе надо пройтись по всему storage и сравнивать индекс каждого с индексом manufacturer, которого ты принимаешь в методе
и соответственно, если индексы совпадают, сетить(как ты сделал)

2021-01-13 17:16 UTC, YuraBondarenko commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +
empty line

2021-01-13 18:07 UTC, AndriiBardin commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +    }
fixed

2021-01-13 18:11 UTC, AndriiBardin commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +
fixed

2021-01-13 19:19 UTC, YuraBondarenko approved these changes

2021-01-14 07:12 UTC, Sofasmile requested changes

2021-01-14 07:12 UTC, Sofasmile commented on pom.xml
> +            <groupId>junit</groupId>
нам не потрібня ця залежність в помніку, давай видалимо її

2021-01-14 07:12 UTC, Sofasmile commented on pom.xml
>  </project>
варто додати пусту строку вкінці файлу

2021-01-14 07:12 UTC, Sofasmile commented on src/main/java/taxi/model/Car.java
> +    private long id;
ід повинно бути обгорткою, а не примітивом (стосується всіх моделей, а також гетерів і сетерів)

2021-01-14 07:12 UTC, Sofasmile commented on src/main/java/taxi/model/Car.java
> +        this.drivers = drivers;
будь уважним з чеклістом:
```suggestion
    public Car(String model, Manufacturer manufacturer) {
        this.model = model;
        this.manufacturer = manufacturer;
        drivers = new ArrayList<>();
```

2021-01-14 07:54 UTC, AndriiBardin commented on src/main/java/taxi/model/Car.java
> +        this.drivers = drivers;
changed

2021-01-14 07:54 UTC, AndriiBardin commented on src/main/java/taxi/model/Car.java
> +    private long id;
fixed

2021-01-14 07:55 UTC, AndriiBardin commented on pom.xml
>  </project>
deleted

2021-01-14 07:55 UTC, AndriiBardin commented on pom.xml
>  </project>
added

2021-01-14 07:55 UTC, AndriiBardin commented on pom.xml
> +            <groupId>junit</groupId>
deleted

2021-01-14 09:41 UTC, Sofasmile approved these changes
як підфіксиш останні коментарі - можеш мержити ПР і приступати до наступної дз

2021-01-14 09:41 UTC, Sofasmile commented on src/main/java/taxi/model/Car.java
> +    public long getId() {
```suggestion
    public Long getId() {
```

2021-01-14 09:41 UTC, Sofasmile commented on src/main/java/taxi/model/Driver.java
> +    public long getId() {
```suggestion
    public Long getId() {
```

2021-01-14 09:41 UTC, Sofasmile commented on src/main/java/taxi/model/Manufacturer.java
> +    public long getId() {
```suggestion
    public Long getId() {
```

2021-01-14 10:05 UTC, merged