Hw8 1st attempt
AndriiBardin/hw-dao3 pull request #7
Opened 2021-01-21 15:03 UTC by AndriiBardin

2021-01-21 15:40 UTC, tbondare requested changes
Измени свой index.jsp - на главной странице у тебя должны быть ссылки на все другие страницы. Напрмер, ты по ссылке кликаешь на create driver и должен осуществится переход на твой create driver.

2021-01-21 15:40 UTC, tbondare commented on src/main/java/taxi/controller/car/AddDriverToCarController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/addDriverToCar.jsp").forward(req, resp);
cars/addDriverToCar.jsp - путь должен быть в виде car/driver/add
1. название папок в WEB_INF не должны быть во множественном числе
2. в car нужно созать папку с driver и уже в ней поместить файл add.jsp

2021-01-21 15:40 UTC, tbondare commented on src/main/java/taxi/controller/car/AddDriverToCarController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/addDriverToCar.jsp").forward(req, resp);
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/car/driver/add.jsp").forward(req, resp);
```

2021-01-21 15:40 UTC, tbondare commented on src/main/java/taxi/controller/car/CreateCarController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/createCar.jsp").forward(req, resp);
нужно ограничиться одним словом в названии jsp-файла, т.к. и так понятно, что ты обращаешься к car  
Это нужно сделать для всех jsp файлов

2021-01-21 15:40 UTC, tbondare commented on src/main/java/taxi/controller/car/CreateCarController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/createCar.jsp").forward(req, resp);
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/cars/create.jsp").forward(req, resp);
```

2021-01-21 15:40 UTC, tbondare commented on src/main/java/taxi/controller/driver/AllDriversController.java
> +
redundant line

2021-01-21 19:01 UTC, tbondare approved these changes

2021-01-22 07:51 UTC, KseniiaMakarova approved these changes

2021-01-22 07:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/view/car/all.jsp
> +</html>
add empty line to the end

2021-01-22 07:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/view/car/all.jsp
> +        <th>Delete</th>
let's remove this if we don't have this feature yet

2021-01-22 07:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/view/driver/all.jsp
> +</html>
empty line

2021-01-22 07:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/view/manufacturer/all.jsp
> +</html>
same

2021-01-22 07:51 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/view/index.jsp
> +<a href="http://localhost:8080/manufacturers/create">Create new manufacturer</a><br>
```suggestion
<a href = "${pageContext.request.contextPath}/manufacturers/create">Create new manufacturer</a><br>
```
and so on

2021-01-22 07:52 UTC, KseniiaMakarova reviewed
good job on this task!

2021-01-22 08:14 UTC, AndriiBardin commented on src/main/webapp/WEB-INF/view/car/all.jsp
> +        <th>Delete</th>
почав реалізацію цієї функції, але не встигав з домашкою, і забув видалити.

2021-01-22 08:53 UTC, merged